---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/apps/{id}/api_key":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    post:
      summary: Obtain a new API key
      tags:
      - API Keys
      security:
      - access_token: []
        client: []
        expiry: []
        uid: []
      responses:
        '200':
          description: API key issued
          content:
            application/json:
              example:
                api_key: eyJhbGciOiJSUzI1NiJ9.eyJhcHAiOiIzYjA1MmNiNDliY2FjMiIsImV4cCI6MTY0NTU2MjEzMn0.LXyLBTIctJDDGgpsBebrWw3JiMPFzKAHwS7JR2m7F_0q59ZJC-ESaXTVtfSGUlBEl2vB7du6emo0DNAiIIoNDRE0fUllteeMmUojAz8f2e3CGY7ZN4YFt12uM4mTuCmJd7vWVMXDT2LGIPQjE8Z6BFPzncZdQczktDCV98O6TfQwGd-MXV0BSICTbvCE6Ue4MaMtQ8VWFQzRdzSvoB2NARCMpV8XhCvoVem3sF5j-1dLsI5_YQiPfyS30ek_9Tt6A82L6QmeXbaoNMSfrvR-XfPv4sQSWgLKSF_Ap0V8CN8MirxBrBd11zv4WxNetUzvYYLdVNd3pduJUeQOj3XQTA
              schema:
                type: object
                properties:
                  api_key:
                    type: string
    put:
      summary: Refresh an expired API key
      tags:
      - API Keys
      parameters: []
      security:
      - app_api_key: []
      responses:
        '200':
          description: New API key issued and stored in credentials
          content:
            application/json:
              example:
                api_key: eyJhbGciOiJSUzI1NiJ9.eyJhcHAiOiIxOTdiMmE3M2E3MDQ2ZCIsImV4cCI6MTY0NTU2MjEzMn0.C34faCneNhXZPPV3ypUzWQu9ytP64ws3nUd58Xq82rm4imdDv-pVXe10yH2awt2GESX1aVrEop016K5dzhI95q0o6GcyvryZsEuzmvGcZVWFswAAXAP58SPGbpwPW1a02RAsO1T8KFrfGJnEY8Fn4dQMRgw_0RJ6P6ULhV6Vn-tc0vCYPl4gbtJCml5WWDgYlAnxl881RAY3cqvOVJB9N-xwNTdotPjZWK2M94d-yYPngrG90uvBLPv8HoSDd7i0gMRQo3rHpLx8mFLXpNjxX5xF4JotO_Dzqke4FMtl1MTlQOG2rxEFHQgAB-SNcdSxqIZc9P5lHe_H7mx3GAZ3eg
              schema:
                type: object
                properties:
                  api_key:
                    type: string
        '401':
          description: Authentication failed
        '409':
          description: API key does not match key stored in credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                path:
                  type: string
              example:
                path: '1.1'
  "/auth":
    post:
      summary: Register a user
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: user created
          content:
            application/json:
              example:
                status: success
                data:
                  id: 1162
                  provider: email
                  uid: jane.doe@example.test
                  name: Jane Doe
                  email: jane.doe@example.test
                  created_at: '2022-02-15T20:35:34.310Z'
                  updated_at: '2022-02-15T20:35:34.316Z'
                  role: member
                  approval: approved
                  color_theme:
                  allow_password_change: false
                  aws_role:
        '422':
          description: unprocessable entity - email taken; name, email, password blank
            or too short!
          content:
            application/json:
              example:
                status: error
                data:
                  id:
                  provider: email
                  uid: ''
                  name: Jane Doe
                  email: jane.doe@example.test
                  created_at:
                  updated_at:
                  role: member
                  approval: pending
                  color_theme:
                  allow_password_change: false
                  aws_role:
                errors:
                  password:
                  - can't be blank
                  full_messages:
                  - Password can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
              required:
              - email
              - password
              - name
              example:
                email: jane.doe@example.test
                password: supersecret
                name: Jane Doe
  "/auth/sign_in":
    post:
      summary: Sign in a user
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: user logged in
          content:
            application/json:
              example:
                data:
                  id: 1163
                  aws_role: testlambda-ex-1
                  email: user5@example.test
                  provider: email
                  name: Test User
                  uid: user5@example.test
                  role: member
                  approval: approved
                  color_theme:
                  allow_password_change: false
        '401':
          description: unauthorized - email or password is wrong
          content:
            application/json:
              example:
                success: false
                errors:
                - Invalid login credentials. Please try again.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
              example:
                email: user5@example.test
                password: insecure
  "/auth/sign_out":
    delete:
      summary: Sign out a user
      tags:
      - Auth
      security:
      - access_token: []
        client: []
        uid: []
        token_type: []
      responses:
        '200':
          description: user signed out
          content:
            application/json:
              example:
                success: true
        '404':
          description: unauthorized - invalid login credentials in the header
          content:
            application/json:
              example:
                success: false
                errors:
                - User was not found or was not logged in.
  "/credential_sets":
    get:
      summary: Return a list of credential sets for the account
      tags:
      - Credential Sets
      security:
      - access_token: []
        client: []
        expiry: []
        uid: []
      responses:
        '200':
          description: Credential sets returned
          content:
            application/json:
              example:
                credential_sets:
                - id: 58d468dd-8c7f-4ada-9c21-ca2f71ef2e33
                  name: Twilio
                  credential_type: TwilioCredentials
                  created_at: '2022-02-15T20:35:36.779Z'
                  updated_at: '2022-02-15T20:35:36.779Z'
              schema:
                type: object
                properties:
                  credential_sets:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        credential_type:
                          type: string
                      required:
                      - id
                      - name
                      - credential_type
                required:
                - credential_sets
    post:
      summary: Create a new credential set
      tags:
      - Credential Sets
      parameters: []
      security:
      - access_token: []
        client: []
        expiry: []
        uid: []
      responses:
        '200':
          description: Credential set created
          content:
            application/json:
              example:
                credential_set:
                  id: 38f7ec24-6e36-44ec-b50f-98d95cd7253b
                  name: Mailgun
                  credential_type: MailgunCredentials
                  created_at: '2022-02-15T20:35:37.156Z'
                  updated_at: '2022-02-15T20:35:37.156Z'
              schema:
                type: object
                properties:
                  credential_set:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      credential_type:
                        type: string
                    required:
                    - id
                    - name
                    - credential_type
                required:
                - credential_set
        '422':
          description: Invalid credential set body
          content:
            application/json:
              example:
                errors:
                - Name can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                credential_set:
                  type: object
                  properties:
                    name:
                      type: string
                    credential_type:
                      type: string
                  required:
                  - name
                  - credential_type
                credentials:
                  type: object
              required:
              - credential_set
              example:
                credential_set:
                  name: Mailgun
                  credential_type: MailgunCredentials
                credentials:
                  api_key: "+7Ucdca1LUQ="
                  domain: example.test
  "/credential_sets/{set_id}":
    parameters:
    - name: set_id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Access the credential data for a set
      tags:
      - Credential Sets
      security:
      - access_token: []
        client: []
        expiry: []
        uid: []
      responses:
        '200':
          description: Credential data returned for set
          content:
            application/json:
              example:
                credential_set:
                  id: fee34caa-a9a3-488b-950c-1b8220a80287
                  name: Twilio
                  credential_type: TwilioCredentials
                  created_at: '2022-02-15T20:35:37.903Z'
                  updated_at: '2022-02-15T20:35:37.903Z'
                credentials:
                  account_sid: fa8f7fa53659d6de
                  auth_token: Whe8Y5poyQo=
              schema:
                type: object
                properties:
                  credential_set:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      credential_type:
                        type: string
                    required:
                    - id
                    - name
                    - credential_type
                  credentials:
                    type: object
                required:
                - credential_set
                - credentials
        '404':
          description: Incorrect id
    put:
      summary: Update the credential set and/or its credential data
      tags:
      - Credential Sets
      parameters: []
      security:
      - access_token: []
        client: []
        expiry: []
        uid: []
      responses:
        '200':
          description: Credentials updated
          content:
            application/json:
              example:
                credential_set:
                  id: 54d83931-145e-491a-9ff9-d60f03b719e6
                  name: New Name
                  credential_type: TwilioCredentials
                  created_at: '2022-02-15T20:35:38.679Z'
                  updated_at: '2022-02-15T20:35:38.694Z'
              schema:
                type: object
                properties:
                  credential_set:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      credential_type:
                        type: string
                    required:
                    - id
                    - name
                    - credential_type
                required:
                - credential_set
        '422':
          description: Invalid credential set body
          content:
            application/json:
              example:
                errors:
                - Name can't be blank
        '404':
          description: Incorrect id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                credential_set:
                  type: object
                  properties:
                    name:
                      type: string
                    credential_type:
                      type: string
                  required:
                  - name
                  - credential_type
                credentials:
                  type: object
              example:
                credential_set:
                  name: New Name
                  credential_type: TwilioCredentials
                credentials:
                  account_sid: fa8f7fa53659d6de
                  auth_token: Whe8Y5poyQo=
    patch:
      summary: Update a single value within the credential data for a set
      tags:
      - Credential Sets
      parameters: []
      security:
      - app_api_key: []
      responses:
        '200':
          description: Credentials updated
          content:
            application/json:
              example:
                ok: true
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                required:
                - ok
        '422':
          description: Invalid path or current value
          content:
            application/json:
              example:
                ok: false
                error: Incorrect value or path
        '404':
          description: Incorrect id
        '401':
          description: Invalid or missing API key
          content:
            application/json:
              example:
                errors:
                - Unauthorized!
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                path:
                  type: array
                  items: string
                credentials:
                  type: object
                  properties:
                    current_value:
                      type: string
                    new_value:
                      type: string
                  required:
                  - current_value
                  - new_value
              required:
              - path
              - credentials
              example:
                path:
                - code_grant
                - access_token
                credentials:
                  current_value: Whe8Y5poyQo=
                  new_value: zTeYlkd9yzo=
    delete:
      summary: Delete the credential set and its credential data
      tags:
      - Credential Sets
      security:
      - access_token: []
        client: []
        expiry: []
        uid: []
      responses:
        '200':
          description: Credentials deleted
        '404':
          description: Incorrect id
  "/credential_sets/{set_id}/api_key":
    parameters:
    - name: set_id
      in: path
      required: true
      schema:
        type: string
    put:
      summary: Refresh an expired API key
      tags:
      - Credential Sets
      parameters: []
      security:
      - app_api_key: []
      responses:
        '200':
          description: New API key issued and stored in credentials
          content:
            application/json:
              example:
                api_key: eyJhbGciOiJSUzI1NiJ9.eyJhcHAiOiIxNWU3OWM2OTI1OTk2ZiIsImV4cCI6MTY0NTU2MjE0Mn0.NdVCMLJlavdQtZANc8L8PKG0SOPHC31MZT-S0LFNEZVCg-zuAnUYuw_ZZjj35mu1kwYG44PGK1XofSiz_l7KhfNHfVUAUfkBG45t9vBMyMrScSD3iuKSW8ZIpTilXGkYmRp7IRKWBNlwun3Qiv1sEQWn0vgX9m9WyANzeIjvdEy8ITJk1dzeu2Tx_97hG8DPiFYqmEyTW3utwjmKM3OEBfS9DzsY9gyiXIPRk5pswUnocJ0NQd3JgwEt4y_6ndeNARcqjyPkGg1yi7Kvj3K8r2R_zguXSSOWsrueEsVxRCbAqAf-20H859l-jK2unrG9SeMFvK2275OkjOl2hoOfVw
              schema:
                type: object
                properties:
                  api_key:
                    type: string
                  required:
                  - api_key
        '401':
          description: Authentication failed
        '409':
          description: API key does not match key stored in credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                path:
                  type: string
              example:
                path: api_key
  "/apps/{id}/credentials":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    patch:
      summary: Refresh an expired API key
      tags:
      - App Credentials
      parameters: []
      security:
      - app_api_key: []
      responses:
        '200':
          description: Single credential value updated
          content:
            application/json:
              example:
                ok: true
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
        '401':
          description: Authentication failed
          content:
            application/json:
              example:
                errors:
                - Unauthorized!
        '400':
          description: Invalid path or incorrect stored value
          content:
            application/json:
              example:
                ok: false
                error: Incorrect value or path
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                path:
                  type: array
                  items:
                    type: string
                credentials:
                  type: object
                  properties:
                    current_value:
                      type: string
                    new_value:
                      type: string
              example:
                path:
                - '1'
                - '1'
                - access_token
                credentials:
                  current_value: secret
                  new_value: new secret
  "/profiles":
    get:
      summary: Show user profile
      tags:
      - Profile
      security:
      - access_token: []
        client: []
        uid: []
        token_type: []
      responses:
        '200':
          description: show profile
        '400':
          description: bad request
        '401':
          description: unauthorized
        '422':
          description: unprocessable entity - when user try to change the team
    put:
      summary: Update user profile
      tags:
      - Profile
      security:
      - access_token: []
        client: []
        uid: []
        token_type: []
      responses:
        '200':
          description: update profile
        '400':
          description: bad request
        '401':
          description: unauthorized
  "/users":
    get:
      summary: Show the list of the users
      tags:
      - User
      security:
      - access_token: []
        client: []
        uid: []
        token_type: []
      responses:
        '200':
          description: users listed
          content:
            application/json:
              example:
                users:
                - id: 1186
                  name: Test User
                  email: user28@example.test
                  role: admin
                  approval: pending
                  color_theme:
                  created_at: '2022-02-15T20:35:43.994Z'
        '401':
          description: unauthorized or not an admin user
          content:
            application/json:
              example:
                errors:
                - You need to sign in or sign up before continuing.
    post:
      summary: Create a user
      tags:
      - User
      security:
      - access_token: []
        client: []
        uid: []
        token_type: []
      parameters: []
      responses:
        '201':
          description: user created
          content:
            application/json:
              example:
                user:
                  id: 1189
                  name: Jane Doe
                  email: jane.doe@example.test
                  role: member
                  approval: approved
                  color_theme:
                  created_at: '2022-02-15T20:35:44.824Z'
        '400':
          description: bad request
          content:
            application/json:
              example:
                errors:
                - Email can't be blank
        '401':
          description: unauthorized
          content:
            application/json:
              example:
                errors:
                - You need to sign in or sign up before continuing.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
                approval:
                  type: string
              required:
              - email
              - password
              - name
              example:
                name: Jane Doe
                email: jane.doe@example.test
                password: supersecret
                role: member
                approval: approved
  "/users/{userId}":
    get:
      summary: Show the user with userId
      tags:
      - User
      security:
      - access_token: []
        client: []
        uid: []
        token_type: []
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: show user
          content:
            application/json:
              example:
                user:
                  id: 1192
                  name: Test User
                  email: user33@example.test
                  role: member
                  approval: approved
                  color_theme:
                  created_at: '2022-02-15T20:35:45.896Z'
        '404':
          description: No user found with that id
        '401':
          description: unauthorized
          content:
            application/json:
              example:
                errors:
                - You need to sign in or sign up before continuing.
    put:
      summary: Update the User with userId
      tags:
      - User
      security:
      - access_token: []
        client: []
        uid: []
        token_type: []
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: user updated
          content:
            application/json:
              example:
                user:
                  id: 1197
                  name: New Name
                  email: user38@example.test
                  role: member
                  approval: approved
                  color_theme:
                  created_at: '2022-02-15T20:35:47.271Z'
        '400':
          description: bad request
          content:
            application/json:
              example:
                errors:
                - Name can't be blank
                - Name is too short (minimum is 3 characters)
        '404':
          description: No user found with that id
        '401':
          description: unauthorized
          content:
            application/json:
              example:
                errors:
                - You need to sign in or sign up before continuing.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
                approval:
                  type: string
              example:
                name: New Name
    delete:
      summary: Destroy the team with userId
      tags:
      - User
      security:
      - access_token: []
        client: []
        uid: []
        token_type: []
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: user deleted
        '404':
          description: No user found with that id
        '401':
          description: unauthorized
          content:
            application/json:
              example:
                errors:
                - You need to sign in or sign up before continuing.
servers:
- url: "{defaultHost}"
  variables:
    defaultHost:
      default: https://trivial-api-staging.herokuapp.com/
components:
  securitySchemes:
    access_token:
      type: apiKey
      name: access-token
      in: header
    client:
      type: apiKey
      name: client
      in: header
    expiry:
      type: apiKey
      name: expiry
      in: header
    uid:
      type: apiKey
      name: uid
      in: header
    app_api_key:
      type: http
      scheme: bearer
      bearerFormat: JWT
